# Generated by Django 3.2.5 on 2021-08-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0002_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateWorn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_worn', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Garment',
            new_name='ClothingItem',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AddField(
            model_name='dateworn',
            name='clothing_items',
            field=models.ManyToManyField(to='wardrobe.ClothingItem'),
        ),
    ]
