# Generated by Django 3.2.5 on 2021-08-04 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0004_auto_20210804_0126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='weardate',
            options={'ordering': ['date']},
        ),
    ]
