# Generated by Django 3.2.5 on 2021-08-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0005_auto_20210804_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
