# Generated by Django 3.2.5 on 2021-08-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0006_clothingitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='previous_wears',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
