# Generated by Django 3.2.5 on 2021-08-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0007_auto_20210804_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='weardate',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
