# Generated by Django 3.2.5 on 2021-08-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0008_auto_20210804_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('BR', 'Brand'), ('CO', 'Color'), ('TY', 'Type'), ('OT', 'Other')], max_length=200)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.RenameModel(
            old_name='WearDate',
            new_name='ClothingWearDate',
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='clothingitem',
            name='previous_wears',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='tags',
            field=models.ManyToManyField(to='wardrobe.ClothingTag'),
        ),
    ]
