# Generated by Django 3.2.5 on 2021-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0011_alter_clothingitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingtag',
            name='category',
            field=models.CharField(blank=True, choices=[('TY', 'Type'), ('BR', 'Brand'), ('CO', 'Color')], max_length=200),
        ),
    ]
