# Generated by Django 3.2.5 on 2021-08-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0012_alter_clothingtag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='previous_wears',
        ),
        migrations.RemoveField(
            model_name='clothingitem',
            name='purchase_date',
        ),
    ]
