# Generated by Django 3.2.5 on 2021-08-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0014_remove_clothingitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
